const bundesligaTeams = [
	"FC Bayern München",
	"Borussia Dortmund",
	"RB Leipzig",
	"Union Berlin",
	"SC Freiburg",
	"Bayer 04 Leverkusen",
	"VfL Wolfsburg",
	"Eintracht Frankfurt",
	"FSV Mainz 05",
	"Borussia Mönchengladbach",
	"1. FC Köln",
	"TSG 1899 Hoffenheim",
	"Werder Bremen",
	"FC Augsburg",
	"VfB Stuttgart",
	"VfL Bochum",
	"1. FC Heidenheim",
	"SV Darmstadt 98",
];

const zweiteBundesligaTeams = [
	"FC Schalke 04",
	"Hertha BSC",
	"Hamburger SV",
	"Fortuna Düsseldorf",
	"FC St. Pauli",
	"1. FC Kaiserslautern",
	"Hannover 96",
	"SC Paderborn",
	"Holstein Kiel",
	"1. FC Nürnberg",
	"Karlsruher SC",
	"Greuther Fürth",
	"Magdeburg",
	"Eintracht Braunschweig",
	"SV Wehen Wiesbaden",
	"VfL Osnabrück",
	"Hansa Rostock",
	"SV Elversberg",
];

const dritteLigaTeams = [
	"Arminia Bielefeld",
	"Duisburg",
	"FC Ingolstadt",
	"1. FC Saarbrücken",
	"Dynamo Dresden",
	"Viktoria Köln",
	"Waldhof Mannheim",
	"1860 München",
	"VfB Lübeck",
	"Erzgebirge Aue",
	"SC Verl",
	"SpVgg Unterhaching",
	"Borussia Dortmund II",
	"SV Sandhausen",
	"Rot-Weiss Essen",
	"SSV Ulm",
	"FC Erzgebirge Aue",
	"Hallescher FC",
	"SC Freiburg II",
	"Jahn Regensburg",
];

const premierLeagueTeams = [
	"Arsenal",
	"Aston Villa",
	"Bournemouth",
	"Brentford",
	"Brighton & Hove Albion",
	"Burnley",
	"Chelsea",
	"Crystal Palace",
	"Everton",
	"Fulham",
	"Liverpool",
	"Luton Town",
	"Manchester City",
	"Manchester United",
	"Newcastle United",
	"Nottingham Forest",
	"Sheffield United",
	"Tottenham Hotspur",
	"West Ham United",
	"Wolverhampton Wanderers",
];

const ligue1Teams = [
	"Paris Saint-Germain",
	"Olympique Marseille",
	"Olympique Lyonnais",
	"AS Monaco",
	"LOSC Lille",
	"Stade Rennes",
	"RC Lens",
	"OGC Nice",
	"Montpellier HSC",
	"Toulouse FC",
	"Stade Reims",
	"FC Nantes",
	"Strasbourg",
	"Lorient",
	"Stade Brestois",
	"Clermont Foot",
	"Le Havre",
	"FC Metz",
	"AJ Auxerre",
	"ESTAC Troyes",
];

const laLigaTeams = [
	"Real Madrid",
	"FC Barcelona",
	"Atletico Madrid",
	"Sevilla FC",
	"Real Sociedad",
	"Real Betis",
	"Villarreal CF",
	"Athletic Bilbao",
	"Osasuna",
	"Rayo Vallecano",
	"Celta Vigo",
	"Getafe CF",
	"RCD Mallorca",
	"Girona FC",
	"UD Almeria",
	"Cadiz CF",
	"Valencia CF",
	"Granada CF",
	"UD Las Palmas",
	"Deportivo Alaves",
];

const serieATeams = [
	"AC Milan",
	"Inter Milan",
	"Juventus",
	"AS Roma",
	"SSC Napoli",
	"Lazio",
	"Atalanta",
	"Fiorentina",
	"Torino",
	"Bologna",
	"Udinese",
	"Monza",
	"Genoa",
	"Salernitana",
	"Lecce",
	"Sassuolo",
	"Empoli",
	"Hellas Verona",
	"Cagliari",
	"Frosinone",
];
